version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env

  fastapi-app:
    build:
      context: ./webserver
    ports:
      - "80:80"
      # - "4444:4444"  # Map the remote debugger port
    env_file:
      - .env
    depends_on:
      - postgres
